version: '2'
services:
    eheart-app:
        image: eheart
        external_links:
            - eheart-mysql:mysql
            - eheart-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eheart?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    eheart-mysql:
        extends:
            file: mysql.yml
            service: eheart-mysql
    eheart-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: eheart-elasticsearch
